### ISSUE TITLE
[DEVEL] Issue loading key store based on password

### ISSUE THREAD

**Issue by eramosr16** [GoPlugin/Plugin#42]
**Description**
Error opening keystore based on file password passed as arguments to plugin

**Your Environment**
Go: 1.17
Docker: 
NodeJs: 12

**Basic Information**
![Screenshot from 2021-11-09 11-04-21](https://user-images.githubusercontent.com/17813469/140963315-a34c3bbc-910a-42e3-b488-16469f93af3b.png)

[pli-node.log](https://github.com/GoPlugin/Plugin/files/7506368/pli-node.log)

**Steps to Reproduce**
Execute node with this params: plugin node start -p password.txt -a apicredentials
password and apicredentials are the default ones inside the repo.

**Additional Information**
[replace this line with any additional information you would like to provide, such as screenshots illustrating the issue]

**Comment by loks2cool** [comment]
Can you please try with -d flag?. 

Like below..

plugin node start  -d -p password.txt -a apicredentials
